### ISSUE TITLE
Question - Rclone commands

### ISSUE THREAD

**Issue by bymaximus** [rclone/rclone-webui-react#72]
Is there any way to run rclone commands from the gui? Like syncing a remote folder with some local folder?

**Comment by negative0** [comment]
Not currently. 🙂

**Comment by negative0** [comment]
@ncw, should we allow to run rclone commands to be executed directly from the WebUI?. 
I am proposing this, 
A plugin that would allow the user to write a command in a text box in the WebUI. This textbox should have autocomplete feature as well.

Any points regarding the security of such a setup?

**Comment by negative0** [comment]
Or a possible alternative could be an interactive GUI to perform those tasks.

**Comment by ncw** [comment]
@negative0 wrote:
> should we allow to run rclone commands to be executed directly from the WebUI?.
> I am proposing this,
> A plugin that would allow the user to write a command in a text box in the WebUI. This textbox should have autocomplete feature as well.
> 
> Any points regarding the security of such a setup?

That is an interesting idea. I can think of two ways of implementing it

1. execute a separate rclone command with the user specified flags etc
- this would be 100% compatible
- there are probably more security implications doing this but as long as we don't touch the shell then I think they are managable
- this would only have the option of returning the rclone log, so not structured data

2. interpret the command and run the command internally
- this might be more efficent and more secure
- interpreting the command line flags would be hard - rclone has one global set of command line flags so that would probably need to be fixed first or worked around anyway!
- you would see this job in the rc as normal

Both interesting options! What do you think?

**Comment by negative0** [comment]
> execute a separate rclone command with the user-specified flags etc

- While this method will be easier to implement, it will be like using the terminal inside the browser, so no extra features that could be possible otherwise due to running in the browser.

> interpret the command and run the command internally
- This is probably the best method in the long run. We could have an interactive way to interact with the commands.
- We could build a UI for every command using this method because we won't be executing as a CLI command. 

I think we should go forward with method 1, and then develop method 2. Then slowly migrate commands one by one to make them compatible with the web standards, which will give us an independent dashboard for each independent functionality. Eg: mount dashboard.

**Comment by timdonovanuk** [comment]
Ideally the webui would be built around REST principles, supporting various endpoints for executing rclone commands. 

I find it weird that the rclone remote api (e.g. "rclone --rc") still needs an rclone client to control it (this is not typically what is understood by a remote API, imo). I investigated the webui as an option, but also come up with nothing. The best I've found is a couple of half-baked attempts at getting nodejs/express to execute commands to rclone.

**Comment by imthenachoman** [comment]
I was wondering if there was more discussion around this? It would be cool to create sync tasks/jobs from the GUI. Even better if we could schedule them. rclone would become a full fledged backup solution where users wouldn't have to muck with custom scripts and what not.

**Comment by kupietools** [comment]
Wait, what? You can't run commands from the GUI? What's it for, then? "Oh, look at that nice GUI! Now let me go back to the command line so I can actually use rclone. Boy, that sure was nice, looking at that GUI."

**Comment by ncw** [comment]
The rclone GUI doesn't just run rclone with certain command line flags, it runs rclone via the REST API (which `rclone rc` is a command line interface for). So the GUI will never be able to just run rclone commands. However I've been working on the API to make it easier to map command lines to API calls and in particular this commit afd2663057ea1ec9eebd3a637790fb554b216481 would enable the gui to map any parameters to command line options- this will go into a GUI eventually which will be able to show you the equivalent rclone command to the one you just did via the API.

I'm going to close this issue since running rclone commands directly from the gui isn't what it is for.

**Comment by imthenachoman** [comment]
@ncw IIRC, right now rclone rc is hard coded to use things like 127.0.0.1 for certain things like adding a connection -- and so the user never sees the auth popup in the browser. Any way we could update it to connect to the actual IP of where rclone is running?
